---
- include_tasks:        'tasks/common/user_groups.yml'
- include_tasks:        'tasks/common/users.yml'
- include_tasks:        'tasks/common/install_packages.yml'
- include_tasks:        'tasks/common/install_files.yml'
