---
- include_tasks:        '../tasks/user_groups.yml'
- include_tasks:        '../tasks/users.yml'
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/install_files.yml'
